### PR TITLE
Add support for Mac users

### PR DESCRIPTION
**Pull request by jrbaxter0**

### CODE REVIEW

**Comment by jrbaxter0** [comment]
@halcdev Can you run this and show me the output? Just do the `./docker-build.sh` command and lmk what it does. It should print an error, but then be OK.

**Comment by jrbaxter0** [comment]
@dgerblick In order to get the desired output, I had to run like this: `DOCKER_BUILDKIT=0 ./docker-build.sh`. Otherwise buildkit hides the error. I could also run with `--progress=plain`, but then it isn't red and colored nicely. Maybe it is OK to just remove the error and have it fail silently? Seems bad IMO.

**Comment by jrbaxter0** [comment]
`usermod -g primarygroupname username` or maybe this is what we should fall through to. Just change their primary group to match what it is externally. Unless if it is root perhaps.

**Comment by halcdev** [comment]
> @halcdev Can you run this and show me the output? Just do the `./docker-build.sh` command and lmk what it does. It should print an error, but then be OK.

Yep. I got this output:

`readlink: illegal option -- f
usage: readlink [-n] [file ...]
mounting host directory  as container directory /home/haddyalchaer/catkin_ws`

**Comment by jrbaxter0** [comment]
@dgerblick bump this since we need to decide if we want this to silently fail or try to alert the user somehow.

**Comment by jrbaxter0** [comment]
@halcdev Now that you've got stuff working on Mac, are there any other things we should add to the scripts? Like setting up iGLX stuff?

**Comment by jrbaxter0** [comment]
@halcdev can you do the following?
On your mac, in the rocket_league directory
`id $USER`
`ls -l`

Then, run this new build script, go into the docker container and run the following:
`id $USER`

**Comment by halcdev** [comment]
Output of `id $USER`: `uid=501(haddyalchaer) gid=1000(haddyalchaer) groups=1000(haddyalchaer),27(sudo),44(video)`
Output of `ls -l` : 
``` 
total 16
-rw-r--r--  1 haddyalchaer haddyalchaer 1518 Sep 26 17:48 LICENSE
-rw-r--r--  1 haddyalchaer haddyalchaer   53 Oct 13 22:32 README.md
drwxr-xr-x  9 haddyalchaer haddyalchaer  288 Nov  3 22:13 camera_tracking
drwxr-xr-x 11 haddyalchaer haddyalchaer  352 Nov 10 23:19 docker
drwxr-xr-x  5 haddyalchaer haddyalchaer  160 Sep 26 17:48 hardware_interface
-rw-r--r--  1 haddyalchaer haddyalchaer  483 Nov  3 22:13 hosts.yaml
drwxr-xr-x  9 haddyalchaer haddyalchaer  288 Oct 13 22:32 local_planner
drwxr-xr-x 11 haddyalchaer haddyalchaer  352 Nov 10 23:19 racersim
drwxr-xr-x  8 haddyalchaer haddyalchaer  256 Sep 26 17:48 rocket_league_control
drwxr-xr-x 10 haddyalchaer haddyalchaer  320 Oct 31 20:15 rocket_league_drl
drwxr-xr-x 10 haddyalchaer haddyalchaer  320 Sep 26 17:48 rocket_league_estimation
drwxr-xr-x  8 haddyalchaer haddyalchaer  256 Oct 13 22:32 rocket_league_highlevel
drwxr-xr-x  5 haddyalchaer haddyalchaer  160 Nov 10 23:19 rocket_league_launch
drwxr-xr-x  5 haddyalchaer haddyalchaer  160 Sep 26 17:48 rocket_league_msgs
-rwxr-xr-x  1 haddyalchaer haddyalchaer 3886 Nov  3 22:13 start.py ```

**Comment by halcdev** [comment]
I got an error when rebuilding the docker image.
```
 => ERROR [2/3] RUN usermod -l haddyalchaer -u 501 -aG video -md /home/haddyalchaer arc &&     groupmod -n haddyalchaer -g 1000 arc ||    1.1s
------
 > [2/3] RUN usermod -l haddyalchaer -u 501 -aG video -md /home/haddyalchaer arc &&     groupmod -n haddyalchaer -g 1000 arc ||     {groupmod -n haddyalchaer `getent group 1000 | awk -F ':' '{print $1}'` && usermod -g 1000 haddyalchaer} &&     echo "haddyalchaer:robot" | chpasswd:
#5 1.014 usermod: user 'haddyalchaer}' does not exist
------
executor failed running [/bin/sh -c usermod -l $USER -u $UID -aG video -md /home/$USER $BASE_USER &&     groupmod -n $USER -g $GID $BASE_USER ||     {groupmod -n $USER `getent group $GID | awk -F ':' '{print $1}'` && usermod -g $GID $USER} &&     echo "$USER:$PW" | chpasswd]: exit code: 6 ```

seems like it interpreted that last curly brace as part of the $USER string.

**Comment by jrbaxter0** [comment]
@halcdev can you run `ls -l` again, looking at files that were specifically created while in the Docker container? Such as images in `catkin_ws/data`? You can just boot up the container, `touch` a file, then `ls -l` it outside the container.

**Comment by halcdev** [comment]
Ok, I did `touch plot.png` in `catkin_ws/data/snakesim` within the docker container.
Outside of the docker container, I did `ls -l` in that same directory and got:
```
total 440
-rw-r--r--@ 1 haddyalchaer  staff  57321 Nov  3 18:37 -100) 10) -1) 1) OLD IGNORE.png
-rw-r--r--@ 1 haddyalchaer  staff  56319 Nov  3 19:29 -100) 10) -1) 1.png
-rw-r--r--@ 1 haddyalchaer  staff  45038 Nov  3 18:24 50) 0) 0) 0.png
-rw-r--r--@ 1 haddyalchaer  staff  63021 Nov 14 19:33 plot.png
haddyalchaer@Haddys-MBP-9 snakesim % 
```

**Comment by jrbaxter0** [comment]
> 
> 
> Output of `id $USER`: `uid=501(haddyalchaer) gid=1000(haddyalchaer) groups=1000(haddyalchaer),27(sudo),44(video)` Output of `ls -l` :
> 
> ```
> total 16
> -rw-r--r--  1 haddyalchaer haddyalchaer 1518 Sep 26 17:48 LICENSE
> -rw-r--r--  1 haddyalchaer haddyalchaer   53 Oct 13 22:32 README.md
> drwxr-xr-x  9 haddyalchaer haddyalchaer  288 Nov  3 22:13 camera_tracking
> drwxr-xr-x 11 haddyalchaer haddyalchaer  352 Nov 10 23:19 docker
> drwxr-xr-x  5 haddyalchaer haddyalchaer  160 Sep 26 17:48 hardware_interface
> -rw-r--r--  1 haddyalchaer haddyalchaer  483 Nov  3 22:13 hosts.yaml
> drwxr-xr-x  9 haddyalchaer haddyalchaer  288 Oct 13 22:32 local_planner
> drwxr-xr-x 11 haddyalchaer haddyalchaer  352 Nov 10 23:19 racersim
> drwxr-xr-x  8 haddyalchaer haddyalchaer  256 Sep 26 17:48 rocket_league_control
> drwxr-xr-x 10 haddyalchaer haddyalchaer  320 Oct 31 20:15 rocket_league_drl
> drwxr-xr-x 10 haddyalchaer haddyalchaer  320 Sep 26 17:48 rocket_league_estimation
> drwxr-xr-x  8 haddyalchaer haddyalchaer  256 Oct 13 22:32 rocket_league_highlevel
> drwxr-xr-x  5 haddyalchaer haddyalchaer  160 Nov 10 23:19 rocket_league_launch
> drwxr-xr-x  5 haddyalchaer haddyalchaer  160 Sep 26 17:48 rocket_league_msgs
> -rwxr-xr-x  1 haddyalchaer haddyalchaer 3886 Nov  3 22:13 start.py ```
> ```

Was this done inside the docker container or outside? I need it to be done outside

**Comment by jrbaxter0** [comment]
And can you do the `ls -l` of that directory for both inside and outside of the container? And have a file you created inside, and a file you created outside pls.

**Comment by halcdev** [comment]
Ok I might have ran something from within the docker container by accident. 
So now I'm starting from the beginning.

I ran id `$USER` OUTSIDE of docker and got:
``` uid=501(haddyalchaer) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae) ```

I ran `ls -l` OUTSIDE of docker (but within the rocket_league directory) and got:
``` 
total 32
-rw-r--r--   1 haddyalchaer  staff  1518 Sep 26 13:48 LICENSE
-rw-r--r--   1 haddyalchaer  staff    53 Oct 13 18:32 README.md
drwxr-xr-x   9 haddyalchaer  staff   288 Nov  3 18:13 camera_tracking
drwxr-xr-x  11 haddyalchaer  staff   352 Nov 13 00:19 docker
drwxr-xr-x   5 haddyalchaer  staff   160 Sep 26 13:48 hardware_interface
-rw-r--r--   1 haddyalchaer  staff   483 Nov  3 18:13 hosts.yaml
drwxr-xr-x   9 haddyalchaer  staff   288 Oct 13 18:32 local_planner
drwxr-xr-x   8 haddyalchaer  staff   256 Sep 26 13:48 rocket_league_control
drwxr-xr-x  10 haddyalchaer  staff   320 Oct 31 16:15 rocket_league_drl
drwxr-xr-x  10 haddyalchaer  staff   320 Sep 26 13:48 rocket_league_estimation
drwxr-xr-x   8 haddyalchaer  staff   256 Oct 13 18:32 rocket_league_highlevel
drwxr-xr-x   6 haddyalchaer  staff   192 Nov 13 00:19 rocket_league_launch
drwxr-xr-x   5 haddyalchaer  staff   160 Sep 26 13:48 rocket_league_msgs
drwxr-xr-x  12 haddyalchaer  staff   384 Nov 13 00:19 rocket_league_simulation
drwxr-xr-x  10 haddyalchaer  staff   320 Nov 13 00:19 rocket_league_visualization
-rwxr-xr-x   1 haddyalchaer  staff  3886 Nov  3 18:13 start.py 
```

I also ran `ls -l` in the `data/snakesim` directory (outside of docker) and got:
```
-rw-r--r--@ 1 haddyalchaer  staff  57321 Nov  3 18:37 -100) 10) -1) 1) OLD IGNORE.png
-rw-r--r--@ 1 haddyalchaer  staff  56319 Nov  3 19:29 -100) 10) -1) 1.png
-rw-r--r--@ 1 haddyalchaer  staff  45038 Nov  3 18:24 50) 0) 0) 0.png
-rw-r--r--@ 1 haddyalchaer  staff  63021 Nov 14 19:33 plot.png
```

Within the docker container, this same command outputs:
```
-rw-r--r-- 1 haddyalchaer haddyalchaer 57321 Nov  3 22:37 '-100) 10) -1) 1) OLD IGNORE.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 56319 Nov  3 23:29 '-100) 10) -1) 1.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 45038 Nov  3 22:24 '50) 0) 0) 0.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 63021 Nov 15 00:33  plot.png
```

I then touched plot.png WITHIN the docker container.

I then did `ls -l` OUTSIDE of the docker container and got:
```
total 440
-rw-r--r--@ 1 haddyalchaer  staff  57321 Nov  3 18:37 -100) 10) -1) 1) OLD IGNORE.png
-rw-r--r--@ 1 haddyalchaer  staff  56319 Nov  3 19:29 -100) 10) -1) 1.png
-rw-r--r--@ 1 haddyalchaer  staff  45038 Nov  3 18:24 50) 0) 0) 0.png
-rw-r--r--@ 1 haddyalchaer  staff  63021 Nov 16 21:50 plot.png
```

I also did `ls -l` WITHIN the docker container and got:
```
total 220
-rw-r--r-- 1 haddyalchaer haddyalchaer 57321 Nov  3 22:37 '-100) 10) -1) 1) OLD IGNORE.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 56319 Nov  3 23:29 '-100) 10) -1) 1.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 45038 Nov  3 22:24 '50) 0) 0) 0.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 63021 Nov 17 02:50  plot.png
```


I then touched plot.png again, this time from OUTSIDE of the docker container. 

`ls -l` OUTSIDE the docker container gives:
```
total 440
-rw-r--r--@ 1 haddyalchaer  staff  57321 Nov  3 18:37 -100) 10) -1) 1) OLD IGNORE.png
-rw-r--r--@ 1 haddyalchaer  staff  56319 Nov  3 19:29 -100) 10) -1) 1.png
-rw-r--r--@ 1 haddyalchaer  staff  45038 Nov  3 18:24 50) 0) 0) 0.png
-rw-r--r--@ 1 haddyalchaer  staff  63021 Nov 16 21:52 plot.png
```

`ls -l` WITHIN the docker container gives:
```
total 220
-rw-r--r-- 1 haddyalchaer haddyalchaer 57321 Nov  3 22:37 '-100) 10) -1) 1) OLD IGNORE.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 56319 Nov  3 23:29 '-100) 10) -1) 1.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 45038 Nov  3 22:24 '50) 0) 0) 0.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 63021 Nov 17 02:52  plot.png
```

**Comment by halcdev** [comment]
I also forgot to add the output of `id $USER` from within the docker container. It looks the same as when I did it a few days ago though:
`uid=501(haddyalchaer) gid=1000(haddyalchaer) groups=1000(haddyalchaer),27(sudo),44(video)`

**Comment by jrbaxter0** [comment]
@halcdev try this one out

**Comment by halcdev** [comment]
The build works now!

I don't know if you need me to run any more of these tests with the new docker build, but I did anyways just in case.

Running `id $USER` inside and outside of the docker container gives (like before):
`uid=501(haddyalchaer) gid=1000(haddyalchaer) groups=1000(haddyalchaer),27(sudo),44(video)`

Touched a file inside the container. Went from this:
```
total 420
-rw-r--r-- 1 haddyalchaer haddyalchaer 57321 Nov  3 22:37 '-100) 10) -1) 1) OLD IGNORE.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 56319 Nov  3 23:29 '-100) 10) -1) 1.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 45038 Nov  3 22:24 '50) 0) 0) 0.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 92138 Nov 17 23:50 'plot copy.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 72050 Nov 17 23:59  plot.png
```

To this:
```
total 420
-rw-r--r-- 1 haddyalchaer haddyalchaer 57321 Nov  3 22:37 '-100) 10) -1) 1) OLD IGNORE.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 56319 Nov  3 23:29 '-100) 10) -1) 1.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 45038 Nov  3 22:24 '50) 0) 0) 0.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 92138 Nov 17 23:50 'plot copy.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 72050 Nov 21 17:10  plot.png
```

Both of those `ls -l` commands were run inside the container.
Outside of the container, the output looks like this:
```
total 840
-rw-r--r--@ 1 haddyalchaer  staff  57321 Nov  3 17:37 -100) 10) -1) 1) OLD IGNORE.png
-rw-r--r--@ 1 haddyalchaer  staff  56319 Nov  3 18:29 -100) 10) -1) 1.png
-rw-r--r--@ 1 haddyalchaer  staff  45038 Nov  3 17:24 50) 0) 0) 0.png
-rw-r--r--@ 1 haddyalchaer  staff  92138 Nov 17 17:50 plot copy.png
-rw-r--r--@ 1 haddyalchaer  staff  72050 Nov 21 11:10 plot.png
``` 

I then touched 'plot.png' again, this time from outside the container. Running `ls -l` outside the container now gives:
```
total 840
-rw-r--r--@ 1 haddyalchaer  staff  57321 Nov  3 17:37 -100) 10) -1) 1) OLD IGNORE.png
-rw-r--r--@ 1 haddyalchaer  staff  56319 Nov  3 18:29 -100) 10) -1) 1.png
-rw-r--r--@ 1 haddyalchaer  staff  45038 Nov  3 17:24 50) 0) 0) 0.png
-rw-r--r--@ 1 haddyalchaer  staff  92138 Nov 17 17:50 plot copy.png
-rw-r--r--@ 1 haddyalchaer  staff  72050 Nov 21 11:10 plot.png
```

And from back within the container, `ls -l` shows this for the file I touched from outside of the container:
```
total 420
-rw-r--r-- 1 haddyalchaer haddyalchaer 57321 Nov  3 22:37 '-100) 10) -1) 1) OLD IGNORE.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 56319 Nov  3 23:29 '-100) 10) -1) 1.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 45038 Nov  3 22:24 '50) 0) 0) 0.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 92138 Nov 17 23:50 'plot copy.png'
-rw-r--r-- 1 haddyalchaer haddyalchaer 72050 Nov 21 17:15  plot.png
```

**Pull request merged**
