### PR TITLE
Autonomy main

### PR DESCRIPTION
**Pull request by jrbaxter0**
This is becoming somewhat stable, so we should merge it in before things diverge too much.

### CODE REVIEW

**Comment by jrbaxter0** [comment]
@dgerblick Can you approve the Dockerfile changes and see if we can get that rebuilt as part of the fixes we're doing there. It may also be nice to add `htop` and put those project dependency installs up top too. And since we aren't using Tensorflow, we may not even need to build off of the CUDA image. I really don't know.

**Comment by jrbaxter0** [comment]
@halcdev Can you see if it renders on Mac? It renders on Ubuntu w/ GPU pass through (If I downgrade Pyglet to a non-broken version), and it surprisingly renders on WSL2.

You will need to run:
```
sudo apt install python3-tk
pip3 install stable-baselines3
```
to make up for the changes in the Dockerfile.

**Comment by jrbaxter0** [comment]
@halcdev specific commands to test are:
`roslaunch rocket_league_drl cartpole.launch`
`rosrun rocket_league_drl train.py`

**Comment by halcdev** [comment]
> @halcdev Can you see if it renders on Mac? It renders on Ubuntu w/ GPU pass through (If I downgrade Pyglet to a non-broken version), and it surprisingly renders on WSL2.
> 
> You will need to run:
> 
> ```
> sudo apt install python3-tk
> pip3 install stable-baselines3
> ```
> 
> to make up for the changes in the Dockerfile.

Stable-Baselines3 worked fine, but entering root password with sudo is not working at all for some reason, so I can't get the command to run with the correct permissions.

**Comment by jrbaxter0** [comment]
> 
> 
> > @halcdev Can you see if it renders on Mac? It renders on Ubuntu w/ GPU pass through (If I downgrade Pyglet to a non-broken version), and it surprisingly renders on WSL2.
> > You will need to run:
> > ```
> > sudo apt install python3-tk
> > pip3 install stable-baselines3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to make up for the changes in the Dockerfile.
> 
> Stable-Baselines3 worked fine, but entering root password with sudo is not working at all for some reason, so I can't get the command to run with the correct permissions.

Password is `robot`. Try killing and restarting the container?

**Comment by jrbaxter0** [comment]
@dgerblick I think this may try to install torch early since it is required by stable-baselines3 iirc

**Comment by purduearc** [comment]
re-opening so the action runs

**Comment by jrbaxter0** [comment]
This should work now

**Pull request closed without merging**
