### PR TITLE
Docker refactor

### PR DESCRIPTION
**Pull request by jrbaxter0**
this might greatly simplify the image. Could also break everything.

### CODE REVIEW

**Comment by jrbaxter0** [comment]
image
Certainly seems to reduce the size. I believe this is from not using CUDA as the base? SB3 uses pytorch, which should have CUDA built in, without needing to install separately

**Comment by jrbaxter0** [comment]
image
I think this should work then

**Comment by jrbaxter0** [comment]
Reminder that we need to revert this before merging: d87f732

**Comment by jrbaxter0** [comment]
I changed the branch for the wrong workflow. Should work now

**Comment by jrbaxter0** [comment]
I deleted #91 on the DockerHub, just so it wouldn't get confused if a new image with the same tag only has one platform.

**Review by dgerblick — APPROVED** [review]

**Pull request merged**
