### PR TITLE
Sim updates

### PR DESCRIPTION
**Pull request by hmccarty**
Fixes a few of the requested items:

- Ball bouncing (lower speeds will larger angles of reflection, but overall it looks much better. more tuning can be done if still see issues)
- Wall sliding (added pseudo-friction to prevent extreme sliding, also looks a lot better but could be further tuned if needed)

Also gave the visualizer a little more flare

Plan on adding updated tests in separate PR

### CODE REVIEW

**Comment by jrbaxter0** [comment]
@hmccarty Please include instructions to test in all future PRs. This could be running a test case or manual instructions. I'm going to run the sim and give manual input to the car to see how it behaves.

**Review by jrbaxter0 — CHANGES_REQUESTED** [review]
I like the new field image. Eventually I'd like to update the car too, but that isn't really a pressing issue.

The reason I'm requesting changes is because calling the `sim_reset` service doesn't give the ball a random velocity like when it originally spawns.

I also think the bouncing off walls could use more tweaking, but it is a definite improvement and I don't want to hold back the "ball initial velocity" feature due to that.

**Comment by hmccarty** [comment]
Later today I'm going to refactor the reset and init function to be combined to a single function.

**Comment by jrbaxter0** [comment]
> Later today I'm going to refactor the reset and init function to be combined to a single function.

Do you want me to wait to review until after that? Or do you want to do that as another PR?

**Comment by hmccarty** [comment]
We can go ahead and merge, I'll attach it to the upcoming PR. Honestly was just looking to leave a note for myself, since I'm not at my computer atm.

**Comment by jrbaxter0** [comment]
image
I'm going to merge this in, even though there is a bug in the sim. Both goals result in victory for team A. Took me a very long time to make that happen lol

**Comment by jrbaxter0** [comment]
But the automatic reset seems to work, and the ball bouncing is improved imo

**Review by jrbaxter0 — APPROVED** [review]

**Pull request merged**
